version: '3'

services:
    database:
        image: 'postgres:latest'

        environment: 
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

        ports:
            - ${PORT}:${PORT}

        volumes:
            - ./db-data/:/var/lib/postgres/data/
